from Models.ArbolBinario import ArbolBinario

arbol = ArbolBinario()

print(arbol.buscar(11))

arbol.insertar(15)
arbol.insertar(9)
arbol.insertar(20)
arbol.insertar(6)
arbol.insertar(14)
arbol.insertar(13)
arbol.insertar(17)
arbol.insertar(64)
arbol.insertar(26)
arbol.insertar(72)

print(arbol.buscar(11))
print(arbol.buscar(20))

print(f"Recorrido PreOrden: ", end="")
arbol.preorden()
print()
print(f"Recorrido InOrden: ", end="")
arbol.inorden()
print()
print(f"Recorrido PostOrden: ", end="")
arbol.postorden()
print()
print(arbol.buscar_mayor())
print(arbol.buscar_menor())
print()
print(f"===MÉTODOS COMPLEMENTARIOS===")
arbol.imprimir_hojas()
print(f"Cantidad de nodos hoja:")
print(arbol.contar_hojas())
print(f"El dato de menor valor en el árbol:")
print(arbol.menor_recursivo())
print(f"Altura del árbol:")
print(arbol.calcular_altura())